### ISSUE TITLE
Example with window and not Revit panel

### ISSUE THREAD

**Issue by grizoood** [jtprichard/RevitWPFFW#2]
Hello,

Could you please provide an example on how to create a window.

I tried to add a command in the core project but I cannot refer to a window that is in the ui project.

Thank you

**Comment by jtprichard** [comment]
A very common problem with this pattern - google dialog MVVM pattern, and there are many options (and opinions) out there.  I found a dialog service to be the most common.  The issue I ran into was that most out of the box solutions required binding the service as part of a standalone assembly, vs. Revit which is allowing us to incorporate pages into Revit windows.  I attempted FantasicFiasoc and Prism, neither with any real success (likely my inexperience.)

Please pull the updated code, and see the Readme for basic information on updates.
To make full use of this, you will also need to see my project (just made public in response to your question) here:  https://github.com/jtprichard/MVVMToolkit

I have found a few options to solve what I think you are looking to do:
1.  Assuming your ribbon is in the UI assembly, you can associate a command to open the dialog window in that assembly.  This wasn't my ideal option, as I like having my commands in one place, but a reasonable workaround.
2.  Implement a dialog service.  The MVVM toolkit I reference above implements a basic dialog service that binds the service to the main page view and viewmodel, but ultimately embedded in the base view and viewmodel classes.  The registration is instantiated via the MainPage initialization, which calls a static DialogRegistration class.  You register your view and viewmodels in that class.  The current example implements the pattern with a CustomDialogView (located in .ui) and CustomDialogViewModel (located in .core).  After it is registered, an example of calling the window can be found in the OpenDialogCommand (located in .core Commands).
3. If you are looking for very simple, non custom dialogs, you can find a few in the MVVMToolkit - Dialogs folder.  

I am by no means an expert in any of this - I am self taught and learning every day.  I welcome any feedback.
Please advise if this answers your question so I can close the issue.

**Comment by grizoood** [comment]
I do tests as soon as possible. thk
